name: Pull Request on Branch Push
on:
  push:
    branches-ignore:
      - master
      - main
jobs:
  auto-pull-request:
    name: Pull-Request
    runs-on: ubuntu-latest
    steps:
      # This step will retry until required check passes
      # and will fail the whole workflow if the check conclusion is not a success
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.1
        with:
          ref: master # can be commit SHA or tag too
          check-name: test # name of the existing check
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20 # seconds
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "update/"
          PULL_REQUEST_BRANCH: "master"