name: Pull Request on Branch Push
on:
  push:
    branches-ignore:
      - master
      - main
jobs:
  auto-pull-request:
    name: Pull-Request
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "update/"
          PULL_REQUEST_BRANCH: "master"
