name: Pull Request on Branch Push #note: modify so it will only open request if other tests pass
on:
  push:
    branches-ignore:
      - master
      - main
jobs:
  auto-pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }} #create another workflow to deploy to cloud upon merge to master