name: Deploy to Heroku (Cloud)
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install needed packages
        run: sudo apt install -y psmisc lsof tree sqlite3 sqlite3-doc build-essential gcc g++ make ruby-dev
      - name: Install dpl tool
        run: sudo gem install dpl
      - name: Push to cloud
        run: dpl --provider=heroku --app=${NAME} --api-key=${KEY}
        env:
          NAME: ${{ secrets.HEROKU_API_NAME }}
          KEY: ${{ secrets.HEROKU_API_KEY }}