name: Deploy to Cloud
on:
  push:
    branches:
      - master
			- main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_API_NAME}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}