name: Syntax & Testing #give this pipeline an actual name
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['master']
jobs:
  Linter: #first test - called "Linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run linter
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Testing Tools
        run: npm install
      - name: Run Test Suite
        run: npm test
  auto-pull-request:
    name: Pull-Request
    runs-on: ubuntu-latest
		needs: [Linter, Unit-Tests]
    steps:
      # This step will retry until required check passes
      # and will fail the whole workflow if the check conclusion is not a success
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "update/"
          PULL_REQUEST_BRANCH: "master"