name: Syntax & Testing #give this pipeline an actual name
on:
  push:
    branches-ignore:
      - master
      - main
jobs:
  Linter: #first test - called "Linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run linter
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Testing Tools
        run: npm install
      - name: Run Test Suite
        run: npm test
  auto-pull-request:
    needs: [Linter, Unit-Tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }} #create another workflow to deploy to cloud upon merge to master